//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSearchClient.TradeSearchServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeItem", Namespace="http://schemas.datacontract.org/2004/07/TradeSearchServiceLibrary.Model")]
    [System.SerializableAttribute()]
    public partial class TradeItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BotNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BotURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuyPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SellPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BotName {
            get {
                return this.BotNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BotNameField, value) != true)) {
                    this.BotNameField = value;
                    this.RaisePropertyChanged("BotName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BotURL {
            get {
                return this.BotURLField;
            }
            set {
                if ((object.ReferenceEquals(this.BotURLField, value) != true)) {
                    this.BotURLField = value;
                    this.RaisePropertyChanged("BotURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuyPrice {
            get {
                return this.BuyPriceField;
            }
            set {
                if ((this.BuyPriceField.Equals(value) != true)) {
                    this.BuyPriceField = value;
                    this.RaisePropertyChanged("BuyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Max {
            get {
                return this.MaxField;
            }
            set {
                if ((this.MaxField.Equals(value) != true)) {
                    this.MaxField = value;
                    this.RaisePropertyChanged("Max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SellPrice {
            get {
                return this.SellPriceField;
            }
            set {
                if ((this.SellPriceField.Equals(value) != true)) {
                    this.SellPriceField = value;
                    this.RaisePropertyChanged("SellPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TradeSearchServiceReference.ITradeSearchService")]
    public interface ITradeSearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeSearchService/RefreshDatabase", ReplyAction="http://tempuri.org/ITradeSearchService/RefreshDatabaseResponse")]
        string[] RefreshDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeSearchService/RefreshDatabase", ReplyAction="http://tempuri.org/ITradeSearchService/RefreshDatabaseResponse")]
        System.Threading.Tasks.Task<string[]> RefreshDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeSearchService/GetItems", ReplyAction="http://tempuri.org/ITradeSearchService/GetItemsResponse")]
        TradeSearchClient.TradeSearchServiceReference.TradeItem[] GetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeSearchService/GetItems", ReplyAction="http://tempuri.org/ITradeSearchService/GetItemsResponse")]
        System.Threading.Tasks.Task<TradeSearchClient.TradeSearchServiceReference.TradeItem[]> GetItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITradeSearchServiceChannel : TradeSearchClient.TradeSearchServiceReference.ITradeSearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradeSearchServiceClient : System.ServiceModel.ClientBase<TradeSearchClient.TradeSearchServiceReference.ITradeSearchService>, TradeSearchClient.TradeSearchServiceReference.ITradeSearchService {
        
        public TradeSearchServiceClient() {
        }
        
        public TradeSearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradeSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradeSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradeSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] RefreshDatabase() {
            return base.Channel.RefreshDatabase();
        }
        
        public System.Threading.Tasks.Task<string[]> RefreshDatabaseAsync() {
            return base.Channel.RefreshDatabaseAsync();
        }
        
        public TradeSearchClient.TradeSearchServiceReference.TradeItem[] GetItems() {
            return base.Channel.GetItems();
        }
        
        public System.Threading.Tasks.Task<TradeSearchClient.TradeSearchServiceReference.TradeItem[]> GetItemsAsync() {
            return base.Channel.GetItemsAsync();
        }
    }
}
